version: 0.2

env:
   variables:
     browserType: "CHROME"
     isRemoteDriverRun: "true"
phases:
  build:
    commands:
      - cd Docker
      - docker-compose up -d
      - sdk install gradle 7.0.2
      - gradlew test