version: 0.2

env:
  variables:
    browserType: "CHROME"
    isRemoteDriverRun: "true"
    remoteWebDriverHost: http://localhost:4444/wd/hub
    mapApiBaseUrl: http://localhost
phases:
  install:
    commands:
      - curl -s "https://get.sdkman.io" | bash && source /root/.sdkman/bin/sdkman-init.sh && sdk install gradle 7.0.2 && sdk install java 11.0.11.hs-adpt
      - docker pull selenium/standalone-chrome:latest\
  pre_build:
    commands:
      - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm --name selenium selenium/standalone-chrome:latest
      - docker exec -u 0 selenium /bin/bash -c 'apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*'
      - docker exec -d selenium ffmpeg -video_size 1360x1020 -framerate 15 -f x11grab -i :99.0 -vf format=yuv420p /home/seluser/recording.mp4
  build:
    commands:
      - gradle -DremoteWebDriverHost="http://localhost:4444/wd/hub" -DmapApiBaseUrl="http://localhost" test