version: 0.2

env:
  variables:
    browserType: "CHROME"
    isRemoteDriverRun: "true"
phases:
  install:
    commands:
      - curl -s "https://get.sdkman.io" | bash && source /root/.sdkman/bin/sdkman-init.sh && sdk install gradle 7.0.2 && sdk install java 11.0.7.hs-adpt
  build:
    commands:
      - cd Docker
      - docker-compose up -d
      - cd ..
      - gradle test